Gelf logging
olxbr/scala-utils pull request #3
Opened 2018-08-27 21:01 UTC by resilva87

This PR refactors the Gelf logger (previously Gelf formatter),
abstracting the way we pulled the `application`, `product` and `environment` names, making it easier for the clients of this library to simply log their needs without needing to constantly messing with these
variables. Additionally, this commit makes mandatory for the users to provide an `application.conf` file in order to define these variables.

2018-08-27 21:36 UTC, iamthiago requested changes

2018-08-27 21:36 UTC, iamthiago commented on src/main/scala/com/grupozap/scalautils/configuration/ConfigUtils.scala
> +object ConfigUtils {
This class should not exist. We have to use only:

```
val config = ConfigFactory.load()
```

2018-08-28 11:37 UTC, alexandreesl approved these changes
Looks great to me 😊👍!

2018-08-28 14:47 UTC, iamthiago approved these changes

2018-08-28 14:49 UTC, merged